# -*- coding: utf-8 -*-
"""Bateria de aceite do briefing de conteudo (v21; parede de trabalhos, telas do /stack na v24).

Roda:  python aceite.py
Complementa o verificar.py — aquele cuida do hero, fps e areas protegidas;
este cuida do CONTEUDO: idioma padrao, ordem das secoes, indicadores,
estrutura dos cases, decisoes, links e responsividade em 4 larguras.

Sai com codigo 1 se alguma checagem falhar.
"""
import sys
from playwright.sync_api import sync_playwright
import os
F = "file:///" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "mockup.html").replace("\\", "/")
falhas = []


def ok(cond, msg, extra=""):
    print(("  OK  " if cond else "  XX  ") + msg + ("   " + str(extra) if extra != "" else ""))
    if not cond:
        falhas.append(msg)


with sync_playwright() as p:
    b = p.chromium.launch()
    pg = b.new_page(viewport={"width": 1280, "height": 800})
    errs = []
    pg.on("console", lambda m: errs.append(m.text) if m.type == "error" else None)
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.goto(F)
    pg.wait_for_timeout(2600)
    pg.mouse.move(700, 300)

    print("\n-- idioma --")
    ok(pg.evaluate("document.documentElement.lang") == "pt-BR", "portugues e o padrao")
    ok(pg.evaluate("document.getElementById('lang').textContent.trim()") == "EN", "botao oferece EN")
    ok("Transformo copy" in pg.evaluate("document.querySelector('.one-line').textContent"), "hero em PT")
    ok(pg.evaluate("document.querySelector('.wall img').alt").startswith("Vídeo gerado por IA"), "alt traduzido")
    ok(pg.evaluate("document.querySelector('.monitor-badge').textContent") == "● no monitor", "selo do monitor em PT")
    vazio = pg.evaluate("[...document.querySelectorAll('[data-pt]')].filter(n=>!n.dataset.pt.trim()).length")
    ok(vazio == 0, "nenhum data-pt vazio", vazio)
    pg.click("#lang")
    pg.wait_for_timeout(500)
    ok(pg.evaluate("document.documentElement.lang") == "en", "botao troca para EN")
    ok("I turn copy" in pg.evaluate("document.querySelector('.one-line').textContent"), "hero volta ao EN")
    ok(pg.evaluate("document.querySelector('.wall img').alt").startswith("AI-generated"), "alt volta ao EN")
    ok(pg.evaluate("document.querySelector('.monitor-badge').textContent") == "● on monitor", "selo do monitor em EN")
    pg.click("#lang")
    pg.wait_for_timeout(500)

    print("\n-- ordem e navegacao --")
    ordem = pg.evaluate("[...document.querySelectorAll('section.sec')].map(s=>s.id||'track').join(',')")
    ok(ordem == "reel,work,do,career,contact", "ordem das secoes", ordem)
    nav = pg.evaluate("[...document.querySelectorAll('.nav-links a')].map(a=>a.getAttribute('href')).join(',')")
    ok(nav == "#reel,#work,#do,#career,#contact", "ordem da nav", nav)

    print("\n-- indicadores --")
    ok(pg.evaluate("!!document.querySelector('#reel .stats')"), "indicadores dentro do /reel")
    ok(pg.evaluate("document.querySelectorAll('.stats').length") == 1, "nao duplicados em outra secao")
    pg.evaluate("document.querySelector('#reel .stats').scrollIntoView({block:'center',behavior:'instant'})")
    pg.wait_for_timeout(1900)
    fim = pg.evaluate("[...document.querySelectorAll('[data-count]')].map(e=>e.textContent)")
    ok(fim == ["1500+", "12", "9", "3+"], "terminam nos valores certos", fim)
    ok(pg.evaluate("[...document.querySelectorAll('[data-count]')].every(e=>e.getAttribute('aria-hidden')==='true')"),
       "contagem escondida do leitor de tela")
    sr = pg.evaluate("[...document.querySelectorAll('.stat .sr')].map(e=>e.textContent).join(',')")
    ok(sr == "1500+,12,9,3+", "leitor de tela recebe o valor final", sr)

    print("\n-- /reel: a ilha de edicao --")
    ok(pg.evaluate("document.querySelector('#reel h2').textContent") == "Trabalhos.", "titulo Trabalhos.")
    ok(pg.evaluate("document.querySelectorAll('.wall figure.clip').length") == 47, "47 cards (44 trechos + 3 sequencias)")
    todos = pg.evaluate("[...document.querySelectorAll('.wall .clip')].filter(c=>!c.hidden).length")
    ok(todos == 27, "Todos: 27 cards, sem repetir personagem/produto/B-roll", todos)
    ok(pg.evaluate("[...document.querySelectorAll('.wall .clip.seq')].filter(c=>!c.hidden).length") == 3, "3 cards de cortes em Todos")
    ok(pg.evaluate("[...document.querySelectorAll('.clip.seq')].every(c=>c.querySelectorAll('.segs i').length===6)"), "barra de 6 cortes nos cards de sequencia")
    ok(pg.evaluate("new Set([...document.querySelectorAll('.wall .clip')].map(c=>c.style.getPropertyValue('--r'))).size") == 3, "3 proporcoes (9:16, 4:5, 1:1)")
    ok(pg.evaluate("document.querySelectorAll('.wall a').length") == 0, "card sem destino nao finge ser link")
    ok(pg.evaluate("[...document.querySelectorAll('.wall img')].every(i=>i.alt.trim().length>20)"), "todo poster tem alt")
    ok(pg.evaluate("[...document.querySelectorAll('.wall figcaption b')].every(b=>b.textContent.trim())"), "todo card tem tipo no rotulo")
    ok(pg.evaluate("[...document.querySelectorAll('.wall figcaption em')].every(b=>/^\\d+:\\d+ · /.test(b.textContent.trim()))"), "todo card mostra proporcao e duracao")
    ok(pg.evaluate("[...document.querySelectorAll('.wall .clip')].every(c=>c.tabIndex===0&&c.getAttribute('role')==='button')"), "todo card abre no teclado")
    ok(pg.evaluate("document.querySelectorAll('.chip').length") == 7, "7 filtros")
    nomes = pg.evaluate("[...document.querySelectorAll('.chip > span')].map(c=>c.textContent.trim()).join('|')")
    ok(nomes == "Todos|Avatares|UGC|Inserts 3D|Produto|Personagem|B-roll", "filtros com os nomes aprovados", nomes)
    ok(pg.evaluate("[...document.querySelectorAll('.chip sup')].map(c=>c.textContent).join()") == "27,8,8,8,8,6,6", "contagem em cada filtro")
    ok(pg.evaluate("!!document.querySelector('#monitor .mon-stage .mon-clip')"), "monitor de programa")
    ok(pg.evaluate("document.getElementById('mon-n').textContent") == "01 / 27", "monitor abre no 1 de 27")
    ok(pg.evaluate("document.querySelector('.mi:not([hidden])').dataset.k") == "avatar-1", "monitor abre no primeiro avatar do bloco")
    ok(pg.evaluate("getComputedStyle(document.getElementById('monitor')).position") == "sticky", "monitor fixo ao lado da folha")
    ok(pg.evaluate("[...document.querySelectorAll('.wall-block:not([hidden])')].map(c=>c.dataset.group).join()") == "avatar,ugc,insert,seq", "Todos agrupado na ordem aprovada")
    ok(pg.evaluate("[...document.querySelectorAll('.wall-row')].every(r=>r.children.length>=2&&r.clientHeight<=224)"), "fileiras balanceadas, sem card sozinho nem altura excessiva")

    pg.evaluate("scrollTo({top:0,behavior:'instant'})")
    pg.wait_for_timeout(500)
    ok(pg.evaluate("[...document.querySelectorAll('#reel video')].every(v=>v.paused)"), "longe da secao: nenhum video tocando")
    pg.evaluate("document.getElementById('mural').scrollIntoView({block:'center',behavior:'instant'})")
    pg.wait_for_timeout(2600)
    tocando = pg.evaluate("[...document.querySelectorAll('.wall video')].filter(v=>!v.paused).length")
    ok(tocando >= 2, "na folha: o que esta sob a faixa do meio toca sozinho", tocando)
    ok(tocando <= 14, "na folha: so a faixa do meio toca, nao todos", tocando)
    ok(pg.evaluate("(()=>{const v=document.querySelector('#mon-clip video');return !!v&&!v.paused})()"), "o monitor toca o trecho escolhido")
    ok(pg.evaluate("document.getElementById('mon-t').textContent") != "00:00:00:00", "timecode do monitor anda")
    pg.evaluate("document.querySelector('.wall .clip.seq').click()")
    pg.wait_for_timeout(1400)
    pg.wait_for_function("(()=>{const c=document.getElementById('mon-clip');const v=c.querySelector('video');if(!v||v.paused)return false;const x=c.querySelector('.xf');return !!x&&x.style.display==='block'})()", timeout=30000, polling=10)
    ok(True, "ASCII entra perto de um corte no monitor")
    pg.evaluate("document.querySelector('#reel .head').scrollIntoView({block:'start',behavior:'instant'})")
    pg.click(".chip[data-f=personagem]")
    pg.wait_for_timeout(1200)
    vis = pg.evaluate("[...document.querySelectorAll('.wall .clip')].filter(c=>!c.hidden).map(c=>c.dataset.src.split('/').pop()).sort().join(',')")
    ok(vis == ",".join(f"personagem-{i}.mp4" for i in range(1, 7)), "filtro Personagem abre as 6 cenas soltas", vis[:60])
    ok(pg.evaluate("[...document.querySelectorAll('.trab-desc p')].filter(p=>!p.hidden).map(p=>p.dataset.f).join()") == "personagem", "a frase acompanha o filtro")
    ok(pg.evaluate("document.querySelector('.mi:not([hidden])').dataset.k") == "personagem-1", "o monitor vai para o primeiro do filtro")
    ok(pg.evaluate("document.getElementById('mon-n').textContent") == "01 / 06", "contador do monitor acompanha o filtro")
    pg.click(".chip[data-f=avatar]")
    pg.wait_for_timeout(1200)
    ok(pg.evaluate("[...document.querySelectorAll('.wall .clip')].filter(c=>!c.hidden).every(c=>c.dataset.cat==='avatar')"), "filtro Avatares so mostra avatar")
    pg.click(".wall .clip:not([hidden]) >> nth=2")
    pg.wait_for_timeout(1500)
    ok(pg.evaluate("document.querySelector('.mi:not([hidden])').dataset.k") == "avatar-3", "clicar num card manda o trecho para o monitor")
    ok(pg.evaluate("document.querySelector('.wall .clip.sel').dataset.src.endsWith('avatar-3.mp4')"), "o card escolhido fica marcado na folha")
    ok(pg.evaluate("getComputedStyle(document.querySelector('.wall .clip.sel img')).filter") == "none", "seleção conserva a cor do card")
    ok(pg.evaluate("getComputedStyle(document.querySelector('.wall .clip.sel .monitor-badge')).display") == "block", "selo aparece no card selecionado")
    ok(pg.evaluate("(()=>{const v=document.querySelector('#mon-clip video');return !!v&&!v.paused&&v.src.endsWith('avatar-3.mp4')})()"), "monitor toca o card clicado")
    pg.click(".chip[data-f=all]")
    pg.wait_for_timeout(1200)
    ok(pg.evaluate("[...document.querySelectorAll('.wall .clip')].filter(c=>!c.hidden).length") == 27, "Todos volta os 27")
    ok(pg.evaluate("document.documentElement.scrollWidth<=document.documentElement.clientWidth"), "sem rolagem horizontal")

    print("\n-- /work: os dois apps --")
    ok(pg.evaluate("[...document.querySelectorAll('.app h3')].map(h=>h.textContent).join(',')") == "LoopVideo,Avatarize", "LoopVideo e Avatarize em destaque")
    hrefs = pg.evaluate("[...document.querySelectorAll('.app-cta a')].map(a=>a.getAttribute('href')).join(' ')")
    ok(hrefs.count("github.com/rafaguiar-dev/") == 4 and hrefs.count("releases/latest") == 2, "baixar + GitHub nos dois", hrefs[:60])
    ok(pg.evaluate("document.querySelectorAll('#app-loop .app-tabs button').length") == 4, "4 abas no palco do LoopVideo")
    ok(pg.evaluate("document.querySelectorAll('#app-avatar .call').length") == 6, "6 etapas no holofote do Avatarize")
    ok(pg.evaluate("document.querySelectorAll('.ax').length") == 3, "3 itens em 'tambem construi'")
    ok(pg.evaluate("[...document.querySelectorAll('.ax-flow')].every(o=>o.children.length>=4)"), "cada um com o fluxo em etapas")
    pg.evaluate("document.getElementById('app-loop').scrollIntoView({block:'center',behavior:'instant'})")
    pg.wait_for_timeout(2500)
    ok(pg.evaluate("!document.querySelector('#app-loop .app-vid').paused"), "o video-guia toca com o app na tela")
    pg.click("#app-loop .app-tabs button[data-t='20']")
    pg.wait_for_timeout(800)
    ok(pg.evaluate("document.querySelector('#app-loop .app-tabs button.on').dataset.t") == "20", "clique na aba pula para ela")
    ok(not pg.evaluate("!!document.getElementById('decisions')"), "/decisions saiu")

    print("\n-- /stack: as tres telas --")
    ok(pg.evaluate("[...document.querySelectorAll('.stg h3')].map(h=>h.textContent).join(',')") == "Gero,Integro,Construo", "Gero, Integro, Construo")
    ok(pg.evaluate("document.querySelectorAll('.stg .stg-tools li').length") == 17, "17 ferramentas, as do perfil do GitHub")
    pg.evaluate("document.querySelector('.pipe').scrollIntoView({block:'center',behavior:'instant'})")
    pg.wait_for_timeout(1500)
    acesos = pg.evaluate("""[...document.querySelectorAll('.scr canvas')].map(c=>{const g=c.getContext('2d'),d=g.getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=16)if(d[i]+d[i+1]+d[i+2]>200)n++;return n})""")
    ok(all(n > 30 for n in acesos), "as tres telas desenham", acesos)
    ok(pg.evaluate("document.querySelectorAll('.stg.hot').length") == 1, "o pulso acende uma etapa por vez")

    print("\n-- links --")
    ok(pg.evaluate("document.querySelectorAll('a[href=\"#\"]').length") == 0, "nenhum href vazio")
    ok(pg.evaluate("document.querySelectorAll('a[href^=\"mailto\"]').length") == 1, "mailto preservado")
    ext = pg.evaluate("[...document.querySelectorAll('a[target=_blank]')].map(a=>a.rel).join('|')")
    ok(set(ext.split("|")) == {"noopener noreferrer"}, "rel completo nos externos", ext[:40])
    ok(pg.evaluate("document.querySelectorAll('.socials a').length") == 2, "so GitHub e LinkedIn (os que tem URL) aparecem")
    ok(pg.evaluate("document.querySelector('.big-mail').href") == "mailto:rafaguiar.dev@gmail.com", "e-mail que existe")

    print("\n-- console --")
    ok(len(errs) == 0, "zero erro de console", errs[:3])
    pg.close()

    for W, H in [(360, 780), (390, 844), (768, 1024), (1280, 800), (1440, 900)]:
        pg = b.new_page(viewport={"width": W, "height": H})
        e2 = []
        pg.on("pageerror", lambda e: e2.append(str(e)))
        pg.goto(F)
        pg.wait_for_timeout(2200)
        over = pg.evaluate("document.documentElement.scrollWidth-innerWidth")
        cols = pg.evaluate("getComputedStyle(document.querySelector('.stats')).gridTemplateColumns.split(' ').length")
        print("\n-- %dx%d --" % (W, H))
        ok(over <= 0, "sem rolagem horizontal", over)
        ok(cols == (2 if W < 760 else 4), "indicadores 2x2 no mobile / 4 no desktop", cols)
        for filtro, quantidade in [("all", 27), ("avatar", 8), ("ugc", 8), ("insert", 8), ("produto", 8), ("personagem", 6), ("broll", 6)]:
            pg.evaluate("f=>document.querySelector('.chip[data-f='+f+']').click()", filtro)
            pg.wait_for_timeout(750)
            ok(pg.evaluate("[...document.querySelectorAll('.wall .clip')].filter(c=>!c.hidden).length") == quantidade, "contagem do filtro " + filtro)
            fechado = pg.evaluate("""()=>[...document.querySelectorAll('.wall-block:not([hidden]) .wall-row')].every(row=>{
                const r=row.getBoundingClientRect(), cs=[...row.children].map(c=>c.getBoundingClientRect());
                return cs.length>=2 && Math.abs(cs[0].left-r.left)<1 && Math.abs(cs.at(-1).right-r.right)<1
                  && cs.every(c=>Math.abs(c.height-r.height)<1) && r.height<=224.1;
            })""")
            ok(fechado, "todas as fileiras fecham: " + filtro)
        ok(len(e2) == 0, "sem erro de pagina", e2[:2])
        pg.close()

    pg = b.new_page(viewport={"width": 1280, "height": 800}, reduced_motion="reduce")
    e3 = []
    pg.on("pageerror", lambda e: e3.append(str(e)))
    pg.goto(F)
    pg.wait_for_timeout(1800)
    pg.evaluate("document.querySelector('#reel .stats').scrollIntoView({block:'center',behavior:'instant'})")
    pg.wait_for_timeout(400)
    print("\n-- reduced motion --")
    vals = pg.evaluate("[...document.querySelectorAll('[data-count]')].map(e=>e.textContent)")
    ok(vals == ["1500+", "12", "9", "3+"], "valor final imediato", vals)
    pg.evaluate("document.getElementById('mural').scrollIntoView({block:'start',behavior:'instant'})")
    pg.wait_for_timeout(900)
    ok(pg.evaluate("document.querySelectorAll('#reel video').length") == 0, "nenhum video criado sozinho (folha e monitor)")
    pg.click(".wall .clip:not([hidden]) >> nth=3")
    pg.wait_for_timeout(1200)
    ok(pg.evaluate("(()=>{const v=document.querySelector('#mon-clip video');return !!v&&!v.paused})()"), "clique no card toca no monitor")
    ok(pg.evaluate("document.querySelectorAll('.wall video').length") == 0, "a folha continua so com posters")
    pg.evaluate("document.getElementById('app-loop').scrollIntoView({block:'center',behavior:'instant'})")
    pg.wait_for_timeout(900)
    ok(pg.evaluate("document.querySelector('#app-loop .app-vid').paused"), "video-guia parado")
    ok(pg.evaluate("[...document.querySelectorAll('.clip')].every(c=>!c.classList.contains('asc-on'))"), "sem camada ASCII")
    ok(pg.evaluate("[...document.querySelectorAll('.ax-flow li')].every(l=>l.classList.contains('lit'))"), "fluxos acesos e parados")
    ok(len(e3) == 0, "sem erro de pagina", e3[:2])
    b.close()

# Bloco independente: 11. encaixe por seção. Contextos novos isolam o storage.
with sync_playwright() as p:
    b = p.chromium.launch()
    for W, H in [(1440, 900), (1280, 800), (1366, 650)]:
        pg = b.new_page(viewport={"width": W, "height": H})
        erros_encaixe = []
        pg.on("pageerror", lambda e: erros_encaixe.append(str(e)))
        pg.goto(F)
        pg.wait_for_timeout(1000)
        lock = pg.locator("#section-lock")
        print("\n-- encaixe %dx%d --" % (W, H))
        ok(lock.count() == 1 and lock.get_attribute("aria-pressed") == "true", "cadeado ligado no desktop")
        ok(lock.get_attribute("aria-label") == "Encaixe por seção: ligado", "rótulo PT e title acompanham o estado")
        ok(lock.get_attribute("title") == lock.get_attribute("aria-label"), "title do cadeado")
        reel = pg.evaluate("scrollY + document.querySelector('#reel').getBoundingClientRect().top - parseFloat(getComputedStyle(document.querySelector('#reel')).scrollMarginTop)")
        pg.mouse.move(W - 30, H // 2)
        pg.mouse.wheel(0, 100)
        pg.wait_for_timeout(1000)
        ok(abs(pg.evaluate("scrollY") - reel) <= 4, "wheel no hero encaixa no /reel", pg.evaluate("scrollY"))
        # A mesma rajada não pode saltar mais de uma parada.
        pg.evaluate("scrollTo({top:0,behavior:'instant'})")
        pg.wait_for_timeout(250)
        for _ in range(10):
            pg.mouse.wheel(0, 60)
            pg.wait_for_timeout(70)
        pg.wait_for_timeout(850)
        ok(abs(pg.evaluate("scrollY") - reel) <= 4, "rajada de wheel produz um encaixe")
        meio = pg.evaluate("(()=>{const s=document.querySelector('#reel'),r=s.getBoundingClientRect();return scrollY+r.top+(r.height-innerHeight)/2})()")
        pg.evaluate("y => scrollTo({top:y,behavior:'instant'})", meio)
        pg.wait_for_timeout(250)
        antes = pg.evaluate("scrollY")
        pg.mouse.wheel(0, 60)
        pg.wait_for_timeout(1000)
        depois = pg.evaluate("scrollY")
        ok(20 < depois - antes < 100, "wheel no meio de seção alta fica livre", depois - antes)
        pg.evaluate("document.querySelector('#career').scrollIntoView({behavior:'instant'})")
        antes = pg.evaluate("scrollY")
        pg.wait_for_timeout(1000)
        ok(abs(pg.evaluate("scrollY") - antes) <= 1, "scrollIntoView por código conserva o destino")
        # Fim de seção alta e subida a partir de seu começo.
        fim = pg.evaluate("scrollY+document.querySelector('#reel').getBoundingClientRect().bottom-innerHeight")
        pg.evaluate("y => scrollTo({top:y,behavior:'instant'})", fim)
        pg.wait_for_timeout(250)
        work = pg.evaluate("scrollY+document.querySelector('#work').getBoundingClientRect().top-72")
        pg.mouse.wheel(0, 60)
        pg.wait_for_timeout(1000)
        ok(abs(pg.evaluate("scrollY") - work) <= 4, "fim da seção alta encaixa na próxima")
        pg.evaluate("y => scrollTo({top:y,behavior:'instant'})", reel)
        pg.wait_for_timeout(250)
        pg.mouse.wheel(0, -60)
        pg.wait_for_timeout(1000)
        ok(pg.evaluate("scrollY") <= 4, "subir do começo do /reel volta ao hero")
        pg.evaluate("document.activeElement.blur()")
        pg.keyboard.press("PageDown")
        pg.wait_for_timeout(1000)
        ok(abs(pg.evaluate("scrollY") - reel) <= 4, "PageDown encaixa no /reel")
        pg.keyboard.press("Home")
        pg.wait_for_timeout(1000)
        ok(pg.evaluate("scrollY") <= 4, "Home volta ao topo")
        pg.mouse.wheel(0, 100)
        pg.wait_for_timeout(120)
        pg.mouse.wheel(0, -60)
        pg.wait_for_timeout(900)
        ok(pg.evaluate("scrollY") <= 4, "gesto contrário cancela a animação")
        lock.click()
        ok(lock.get_attribute("aria-pressed") == "false", "cadeado alterna para livre")
        pg.evaluate("scrollTo({top:0,behavior:'instant'})")
        pg.mouse.wheel(0, 100)
        pg.wait_for_timeout(1000)
        ok(20 < pg.evaluate("scrollY") < reel - 4, "cadeado aberto deixa wheel livre")
        pg.locator("#lang").click()
        pg.wait_for_timeout(50)
        ok(lock.get_attribute("aria-label") == "Section alignment: off", "rótulo do estado traduz para EN")
        ok(not erros_encaixe, "encaixe sem erros de página", erros_encaixe)
        pg.close()
    for opcoes, nome in [({"viewport": {"width": 390, "height": 844}, "is_mobile": True, "has_touch": True}, "toque"),
                         ({"viewport": {"width": 1280, "height": 800}, "reduced_motion": "reduce"}, "movimento reduzido")]:
        pg = b.new_page(**opcoes)
        pg.goto(F)
        lock = pg.locator("#section-lock")
        ok(lock.get_attribute("aria-pressed") == "false", nome + ": desligado por padrão")
        lock.click()
        ok(lock.get_attribute("aria-pressed") == "true", nome + ": cadeado permite ligar")
        ok(pg.evaluate("document.documentElement.scrollWidth<=innerWidth"), nome + ": sem rolagem horizontal")
        pg.close()
    b.close()

print("\n" + "=" * 54)
print("TUDO PASSOU" if not falhas else "FALHOU:\n  - " + "\n  - ".join(falhas))

sys.exit(1 if falhas else 0)
